branches:
  only:
    # Tagged releases
    - /^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$/
    # Master
    - master
    # Release branches
    - /^release\/.+$/
    # Develop
    - develop

language: node_js
node_js:
  - '14'

cache: yarn

install:
  - yarn install

script:
  - echo "No tests ran"

before_deploy:
  if ! [[ ${HAS_RAN_BEFORE_DEPLOY} ]]; then
    export HAS_RAN_BEFORE_DEPLOY="TRUE"

    BLUE='\e[1;34m'
    GREEN='\e[1;32m'
    ENDCOLOUR='\e[1;m'

    apt-get update && apt-get install -y --allow-unauthenticated wget jq unzip less

    echo -e "${BLUE}Installing AWS CLI...${ENDCOLOUR}"
    rm -Rf ${PWD}/aws
    wget -q -O awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    unzip awscliv2.zip
    ${PWD}/aws/install
    aws --version
    rm  awscliv2.zip

    echo -e "${BLUE}Installing CloudFoundry CLI...${ENDCOLOUR}"
    apt-get update && apt-get install -y --allow-unauthenticated gnupg
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
    echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    apt-get update && apt-get install -y --allow-unauthenticated cf7-cli
  fi

deploy:
  # Tagged releases
  - provider: script
    script: ENVIRONMENT=production CF_API=https://api.cloud.service.gov.uk CF_ORGANISATION=$CF_ORGANISATION CF_SPACE=$CF_SPACE_PRODUCTION CF_APP_NAME=$CF_APP_NAME CF_USERNAME=$CF_DEPLOY_USERNAME CF_PASSWORD=$CF_DEPLOY_PASSWORD CF_INSTANCES=$CF_INSTANCES_PRODUCTION CF_ROUTE=$CF_ROUTE_PRODUCTION CF_ENV_SERVICE=$CF_ENV_SERVICE CF_ENV_SERVICE_KEY=$CF_ENV_SERVICE_KEY bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$
  # Develop
  - provider: script
    script: ENVIRONMENT=staging CF_API=https://api.cloud.service.gov.uk CF_ORGANISATION=$CF_ORGANISATION CF_SPACE=$CF_SPACE_STAGING CF_APP_NAME=$CF_APP_NAME CF_USERNAME=$CF_DEPLOY_USERNAME CF_PASSWORD=$CF_DEPLOY_PASSWORD CF_INSTANCES=$CF_INSTANCES_STAGING CF_ROUTE=$CF_ROUTE_STAGING CF_ENV_SERVICE=$CF_ENV_SERVICE CF_ENV_SERVICE_KEY=$CF_ENV_SERVICE_KEY bash .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
